// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aorta-ui/BiotechPro.tsx": () => import("../components/mockups/aorta-ui/BiotechPro.tsx"),
  "./components/mockups/aorta-ui/ClinicalDark.tsx": () => import("../components/mockups/aorta-ui/ClinicalDark.tsx"),
  "./components/mockups/aorta-ui/ModernClean.tsx": () => import("../components/mockups/aorta-ui/ModernClean.tsx")
};
